### PR TITLE
Create Catpun

### PR DESCRIPTION
**Pull request by liamcostello16**
Is this pun good?

### CODE REVIEW

**Comment by jdallison** [comment]
Commit accepted.

**Comment by jdallison** [comment]
Commit accepted.

**Comment by lewisfearon** [comment]
good good

**Comment by k-mccalla** [comment]
good

**Review by jdallison — APPROVED** [review]

**Review by lewisfearon — APPROVED** [review]

**Review by k-mccalla — COMMENTED** [review]
good

**Pull request merged**
